### ISSUE TITLE
手动运行action时，生成书籍出错

### ISSUE THREAD

**Issue by foreveruand** [carey036/GenBooks#2]
错误信息：
Traceback (most recent call last):
  File "/home/runner/work/GenBooks/GenBooks/./src/genBook.py", line 23, in <module>
    feeds = config["feeds"]
TypeError: string indices must be integers
Error: Process completed with exit code 1.
似乎说是必须用数字？我把“feeds"改为数字，仍然报错，是config填写错误了吗？

**Comment by carey036** [comment]
可以看下你的config嘛

**Comment by carey036** [comment]
/src/rss.conf是一个样本，重新fork一下，然后修改rss.conf，新建GITHUBUSER 和 GITHUBEMAIL两个secret就可以使用了

**Comment by foreveruand** [comment]
我重新fork了一下，还是一样的问题，用的rssconf的配置
INFO:root:get env fail, try to read rss.conf
INFO:root:error occurred when reading config
Traceback (most recent call last):
  File "/home/runner/work/GenBooks/GenBooks/./src/genBook.py", line 26, in <module>
    feeds = config["feeds"]
TypeError: string indices must be integers
Error: Process completed with exit code 1.

对了，我是在生成书籍里加了个workflow_dispatch: 手动运行的生成书籍action，这个有影响吗

**Comment by carey036** [comment]
你新建了CONFIG这个secret吗，可以看下内容嘛

**Comment by foreveruand** [comment]
重新fork以后，我没有新建CONFIG这个secret
INFO:root:get env fail, try to read rss.conf
这个信息应该是说读了rss.conf

**Comment by carey036** [comment]
好了，重新fork一下就好了，读取文本的地址写错了

**Comment by carey036** [comment]
我看了一下你fork的，已经没有问题了
还需要建两个secret，GITHUBUSER和GITHUBEMAIL
另外修改一些参数使用就好了

**Comment by foreveruand** [comment]
已经成功了。
使用的outlook邮箱开启了两步认证，推送的时候一直提示登陆失败。最后创建了应用密码才认证成功。
感谢您的帮助
