### ISSUE TITLE
‘This job was skipped’

### ISSUE THREAD

**Issue by hopexavier** [carey036/GenBooks#4]
请问我尝试了不同的cron, 在schedule time的时候，github都有提示‘This job was skipped’。手动运行或者 star的话可以正常运行，这是什么问题呢？谢谢

**Comment by carey036** [comment]
https://github.com/carey036/GenBooks/commit/5045f9e3a5f48f0bcf0b017f46c1f3d551a7c179
删除了if: github.event.repository.owner.id == github.event.sender.id，star运行改为github action手动运行
明天看看能不能自动推送

**Comment by hopexavier** [comment]
已经解决。谢谢！
