### ISSUE TITLE
建议增加RSS抓取时间设置

### ISSUE THREAD

**Issue by hopexavier** [carey036/GenBooks#5]
现有的rss parsing是固定下载最近N小时的新feed，请问是否可以增加config修改这个参数，比如可以允许下载所有rss最近24小时/48/72小时的订阅？谢谢

**Comment by carey036** [comment]
应该可以了。直接在/conf/time.txt 里面修改你想要抓取多少小时前之内的就行了，小时数要小于10000

**Comment by hopexavier** [comment]
谢谢🙏！
