### ISSUE TITLE
关于二级目录

### ISSUE THREAD

**Issue by jackieyiwu** [carey036/GenBooks#6]
可不可以用多个TITLE，每个TITLE下面加入一堆RSS。或者有别的语法可以生成二级目录。

**Comment by carey036** [comment]
是说自定义分类吗
比如说
* 分类1
  * rss1
  * rss2
* 分类2
  * rss3
  * rss4

这种吗，暂时没有计划这么做，需要的话可以去改https://github.com/carey036/GenBooks/blob/main/src/keys.py 和 https://github.com/carey036/GenBooks/blob/main/src/processRss.py 这两个文件。

因为比较麻烦同时感觉不是很有需求，如果能做到兼容的话欢迎pr。

**Comment by carey036** [comment]
补充一下，目前是有单个rss作为标题的，结构如下

* 大标题
  * rss1
    * 文章标题1
    * 文章标题2
  * rss2
    * 文章标题3
    * 文章标题4
  * rss3
    * 文章标题5
    * 文章标题6
